name: ios build scripts

on:
  push:
    branches:
      - development
      - main
    paths:
      - '.github/workflows/ios-build-scripts.yml'
      - 'apple/**'
      - '!apple/README.md'
      - 'scripts/**'
      - 'tools/**'
      - 'apple.sh'
      - 'ios.sh'
  pull_request:
    branches:
      - development
      - main
    paths:
      - '.github/workflows/ios-build-scripts.yml'
      - 'apple/**'
      - '!apple/README.md'
      - 'scripts/**'
      - 'tools/**'
      - 'apple.sh'
      - 'ios.sh'

jobs:
  build-main-on-macos-sonoma:
    name: ios main on ventura
    runs-on: macos-13
    strategy:
      matrix:
        xcode: [ '14.3.1', '15.2' ]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: prerequisites
        run: brew install autoconf automake libtool pkg-config curl git cmake nasm
      - name: set up xcode
        run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh
      - name: run the build script
        run: ./ios.sh --enable-ios-zlib --enable-ios-audiotoolbox --enable-ios-bzip2 --enable-ios-videotoolbox --enable-ios-avfoundation --enable-ios-libiconv --disable-armv7 --disable-armv7s --disable-arm64-mac-catalyst --disable-arm64-simulator --disable-i386 --disable-x86-64 --disable-x86-64-mac-catalyst --enable-fontconfig --enable-freetype --enable-fribidi --enable-gmp --enable-gnutls --enable-lame --enable-libass --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxml2 --enable-opencore-amr --enable-shine --enable-speex --enable-kvazaar --enable-gpl --enable-x264 --enable-xvidcore --enable-x265 --enable-libvidstab --enable-libilbc --enable-opus --enable-snappy --enable-soxr --enable-twolame --enable-vo-amrwbenc --enable-zimg
#--enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-bzip2 --enable-ios-libiconv --enable-ios-videotoolbox --enable-ios-zlib --enable-gpl --disable-armv7 --disable-armv7s --disable-arm64-mac-catalyst --disable-arm64-simulator --disable-i386 --disable-x86-64 --disable-x86-64-mac-catalyst --enable-xvidcore --full --enable-x264 --enable-x265
#--xcframework --enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-bzip2 --enable-ios-libiconv --enable-ios-videotoolbox --enable-ios-zlib
      - name: print build logs
        if: ${{ always() }}
        run: cat build.log
      - name: print ffbuild logs
        if: ${{ failure() }}
        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'